<a href="https://colab.research.google.com/github/AnaCristina1972/Dio-Desafios/blob/main/aula260823.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import *
notas=array(eval(input("Notas: ")))
print(f"Maior nota na sala:{max(notas)} ")
print("")
print(f"Menor nota na sala:{min(notas)} ")
print("")
print(f"Quantidade de alunos na sala:{size(notas)} ")
print("")
print(f"Medias Geral:{sum(notas)/size(notas)} ")

In [ ]:
for i in range(5):
    print(i)


n=int(input("Qtde. de termos "))
soma=0
i=0

while(i<n):
    soma=soma+2**i
    i=i+1

print(soma)


In [ ]:
from numpy import *

v=array(eval(input("Prenche seu vetor --->  Vetor:")))

print(v)
print("")
print(v)

In [ ]:
from numpy import *
notas=array([6.2,2.3,9.4,5.1,8.9,9.8,10.0,7.0,6.3,4.4])

print(notas)
print("")
print(notas[2])
print("")
notas[4]=notas[4]+1.0
notas[7]=notas[7]+1.0
print(notas)


In [6]:
from numpy import *
v=range(5)

print(v)
v=arange(5)
print(v)


range(0, 5)
[0 1 2 3 4]


In [5]:
for i in [1,2,3]:
    print("",i)



 1
 2
 3


In [2]:
for ch in "Python":
    print(ch)




P
y
t
h
o
n


In [1]:
for i in range(0,21,2): # 0 fica é o inicial, 21 é o valor que sera a parada -1, 2 é o incremento
    print(i)

0
2
4
6
8
10
12
14
16
18
20


In [ ]:
from numpy import *
notas=array(eval(input("Informe as notas")))

cred=array(eval(input("Informe as Creditos")))
i=0
numerador=0
denominador=0
while(i<size(notas)):
  numerador=numerador+notas[i]*cred[i]
  denominador=denominador+cred[i]
  i=i+1
coeficiente=numerador/denominador
print(coeficiente,3)

In [ ]:
from numpy import *
votos=array(eval(input("quat. votos")))

print(sum(votos[:-1]))
print(sum(votos[:-3]))
venc=max(votos[:-3])/sum(votos[:-3])*100
print(round(venc,2))


In [ ]:
dna=input("Sequencia DNA").upper()
copia=""
i=0
while i<len(dna)
    if()

In [13]:
s=input("Digite uma string")
inv=""
i=-1
while i >= -len(s):
  inv=inv+s[i]
  i=i-1
print(inv)

Digite uma stringAna Cristina
anitsirC anA


In [16]:
nome_meses='JamFevMerAbrMaiJunJulAgosSetOutNovDez'
data = input("Informe a data (dd/mm/aaaa): ")
dia=int(data[:2])
mes=int(data[3:5])
ano=int(data[-4])
ini=3*(mes-1)
fim=ini +3
mes_abrev = nome_meses[ini : fim]
nova_data= str(dia) + '-' + mes_abrev + '-' + ano
print(nova_data)

Informe a data (dd/mm/aaaa): 26/08/2023


TypeError: ignored

In [17]:
from numpy import *
quadro=array(eval(input("M:")))
print(quadro)



M:[[46,37,38],[27,23,17]]
[[46 37 38]
 [27 23 17]]


In [21]:
from numpy import *
m0=zeros((3,2))
print(m0)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
from numpy import *
m0=ones((3,5))
print(m0)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:

quadro = array([
[46, 37, 38],
[27, 23, 17],
[26, 18, 26],
[19, 18, 19],
[17, 10, 15],
[12, 8, 21],
[10, 18, 14]
])

# Tipos de medalhas (no. de colunas)
MEDALHAS = shape(quadro)[1]
# Variavel acumuladora
total = 0
# Processa a j-esima coluna na linha 4

for j in range(MEDALHAS):
  total = total + quadro[3,j]

print(total)

56


In [ ]:

from numpy import *
# Respostas dos alunos às questões
resp = array ([
['A', 'B', 'A', 'C', 'C', 'D', 'E', 'E', 'A', 'D'],
['D', 'B', 'A', 'B', 'C', 'A', 'E', 'E', 'A', 'D'],
['E', 'D', 'D', 'A', 'C', 'B', 'E', 'E', 'A', 'D'],
['C', 'B', 'A', 'E', 'D', 'C', 'E', 'E', 'A', 'D'],
['A', 'B', 'D', 'C', 'C', 'D', 'E', 'E', 'A', 'D'],
['B', 'B', 'E', 'C', 'C', 'D', 'E', 'E', 'A', 'D'],
['B', 'B', 'A', 'C', 'C', 'D', 'E', 'E', 'A', 'D'],
['E', 'B', 'E', 'C', 'C', 'D', 'E', 'E', 'A', 'D']])
# Gabarito das questões
gab = array(
['D', 'B', 'D', 'C', 'C', 'D', 'A', 'E', 'A', 'D'])

# Constantes
NALUNOS = shape(resp)[0] # No. de alunos
NQUEST = shape(resp)[1] # No. de questoes

# Vetor das notas de cada aluno
notas = zeros((NALUNOS), dtype=int)

# Percorre cada linha (aluno)
for i in range(NALUNOS):
# Pontua um aluno i, verificando cada questao
	for j in range(NQUEST):
		if (resp[i,j] == gab[j]):
			notas[i] = notas[i] + 1
print(notas)
